// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/vnnyx/auth-service/internal/delivery/grpc"
	"github.com/vnnyx/auth-service/internal/infrastructure"
	"github.com/vnnyx/auth-service/internal/repository"
	"github.com/vnnyx/auth-service/internal/usecase"
)

// Injectors from injector.go:

func InitializeGRPCAAuthServer() *grpc.Server {
	client := infrastructure.NewRedisClient()
	authRepository := repository.NewAuthRepository(client)
	authUC := usecase.NewAuthUC(authRepository)
	server := grpc.NewGRPCServer(authUC)
	return server
}
